### ISSUE TITLE
Hey Ya!  Congrats on getting this project off the ground

### ISSUE THREAD

**Issue by Newman5** [txpipe/asteria#2]
If you are interested, perhaps come to the Gimbalabs playground to discuss the project.  I'm planning a session concerning 'Games' and building with Cardano.  

Would you be interested in showcasing / explaining Asteria for us at a Gimbalabs playground?

Here is the Miroboard about it: https://miro.com/app/board/uXjVMnYs6P8=/?moveToWidget=3458764563494604015&cot=14

And, the session I have initiated is March 12th.

cheers!

**Comment by Newman5** [comment]
let me know if I can user test or participate in some way.  Looking forward to your project

**Comment by scarmuega** [comment]
It was a great session @Newman5, thanks for the invite. I hope we can do a more "hands on" session once we have something more advanced.
