### ISSUE TITLE
In order to build `visualizer` on Ubuntu, `librust-alsa-sys-dev` and `libudev-dev` packages are required

### ISSUE THREAD

**Issue by perseus-algol** [txpipe/asteria#45]
In order to build `visualizer` on Ubuntu (23.04), `librust-alsa-sys-dev` and `libudev-dev` packages are required. Details are below. May be it is worth to add this info as a requirements? Actually I am thinking - is there a way to get OS packages dependencies list from `Cargo.lock`? Because it is only in my system two packages was missed, required specifically by two crates: `alsa-sys` and `libudev-sys`, but it could differs on other systems. Or is it a common way to build - just try to build and if it fails, read messages and install missed packages?

```bash
$ cargo build -p visualizer
> error: failed to run custom build command for `alsa-sys v0.3.1`
> pkg-config exited with status code 1
> PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags alsa
>  The system library `alsa` required by crate `alsa-sys` was not found.

$ sudo apt install librust-alsa-sys-dev

$ cargo build -p visualizer
> error: failed to run custom build command for `libudev-sys v0.1.4`
> The system library `libudev` required by crate `libudev-sys` was not found.

$ sudo apt-get install libudev-dev

$ cargo build -p visualizer  # Succeeded
```

**Comment by scarmuega** [comment]
closing since we're moving onto Godot as our game engine.
